#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yunohost_gotify_notifications"
name = "Yunohost_Gotify_Notifications"
description.en = "A collection of Yunohost webhooks to send notifications using Gotify"
description.fr = "Une collection de webhooks Yunohost pour envoyer des notifications en utilisant Gotify"

version = "0.1~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
admindoc = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications/blob/main/README.md"
userdoc = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications/blob/main/README.md"
code = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "1M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.gotify]
    ask.en = "What's the url of your Gotify install ?"
    ask.fr = "Quelle est l'addresse url de votre installation Gotify ?"
    type = "url"

    [install.apptoken]
    ask.en = "App token for this server"
    ask.fr = "Jeton de l'application pour ce serveur"
    type = "string"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications/archive/refs/tags/0.1.tar.gz"
    sha256 = "50c3c8328f344a22136b06b0dc600facb124fd881d6b9b44effbd4e9eeb42a13"
    autoupdate.strategy = "latest_github_tag"

    [resources.data_dir]
